name: TaleofJared
favicon: null
layout_spectrum: 1
typography_spectrum: 0.10054671997204423
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74784557-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5efe3'
    - '#c7bda2'
    - '#140d14'
    - '#988461'
    - '#c24032'
  brandStrength: 0.75
  lightness: 0.7081252704374492
  saturation: 0.4725688840262592
  rhythmicContrast: 0.5
purpose: []
