name: TaleofJared
favicon: null
layout_spectrum: 0.5987680614925921
typography_spectrum: 0.10054671997204423
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3373145356308669
  lightness: 0.7081252704374492
  saturation: 0.4725688840262592
  rhythmicContrast: 0.3721478097140789
purpose: []
